### ISSUE TITLE
[Bug]: id_token is not accessible after resetAuthorizationData function executed

### ISSUE THREAD

**Issue by kcalisan** [damienbod/angular-auth-oidc-client#1607]
### Version

15.0.0

### Steps to reproduce the behavior

```true
private logoffInternal(
    logoutAuthOptions: LogoutAuthOptions,
    endSessionUrl: string,
    config: OpenIdConfiguration,
    allConfigs: OpenIdConfiguration[]
  ): Observable<unknown> {
    const { logoffMethod, customParams } = logoutAuthOptions || {};

    this.resetAuthDataService.resetAuthorizationData(config, allConfigs); //id_token is deleted

    if (!logoffMethod || logoffMethod === 'GET') {
      this.redirectService.redirectTo(endSessionUrl);

      return of(null);
    }

    const { state, logout_hint, ui_locales } = customParams || {};
    const { clientId } = config;
    const idToken = this.storagePersistenceService.getIdToken(config); // id_token cannot be accessible at this point
    const postLogoutRedirectUrl = this.urlService.getPostLogoutRedirectUrl(config);
    const headers = this.getHeaders();
    const { url } = this.urlService.getEndSessionEndpoint(config);
    const body = {
      id_token_hint: idToken,
      client_id: clientId,
      post_logout_redirect_uri: postLogoutRedirectUrl,
      state,
      logout_hint,
      ui_locales,
    };

    const bodyWithoutNullOrUndefined = removeNullAndUndefinedValues(body);

    return this.dataService.post(url, bodyWithoutNullOrUndefined, config, headers);
  }
```

**Comment by FabianGosebrink** [comment]
Bug is fixed in next release.

**Comment by kcalisan** [comment]
> Bug is fixed in next release. PR https://github.com/damienbod/angular-auth-oidc-client/pull/1604

Thank you, but when I choose "POST" method I cannot access to id_token

**Comment by FabianGosebrink** [comment]
Yes, this Bug is fixed in the next release :) We have to test and then we will release. Thanks :)

**Comment by kcalisan** [comment]
Thank you @FabianGosebrink, I get the latest version (15.0.1) but the issue is still the same. If I choose logoffMethod as 'POST' request I can't see id_token_hint parameter in the POST request, only these parameters are being sent to the identity server:  {"client_id":"test-client","post_logout_redirect_uri":"http://localhost:4200"}: 

I am using the following function.

 logout(): void {
      this.oidcSecurityService.logoff(undefined, {  logoffMethod: 'POST'}).subscribe((result) => {
        console.log(result);
  });

**Comment by FabianGosebrink** [comment]
Hey, I just saw, that I had the correct solution and for any reason reverted it! I think I do see the issue. Sorry about this, that was totally my fault.

**Comment by damienbod** [comment]
With the release of 15.0.2, this should work then. 

```ts
  logout() {
    const logoutAuthOptions: LogoutAuthOptions = {
      customParams: {
        logout_hint: 'some-logout-hint',
      },
    };

    this.oidcSecurityService.logoff('', logoutAuthOptions).subscribe((result) => console.log(result));
  }

  logoffAndRevokeTokens() {
    const logoutAuthOptions: LogoutAuthOptions = {
      customParams: {
        logout_hint: 'some-logout-hint',
      },
    };

    this.oidcSecurityService.logoffAndRevokeTokens('', logoutAuthOptions).subscribe((result) => console.log(result));
  }
```

**Comment by kcalisan** [comment]
Hey, no problem at all, thank you for the quick fix.
